<?php

namespace SF\SmartfixBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use Doctrine\ORM\Query\QueryException;

/**
 * SupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportRepository extends EntityRepository
{
    /*
     * 
     * 
     */
    function getSupportLeftJoin(){

        $select = $this->createQueryBuilder('t');
        $select
                ->select('t', 's.id, s.serviceName')
                ->innerJoin('SF\SmartfixBundle\Entity\Service', 's', Expr\Join::WITH, 't.serviceId = s.id');
        
        return $select->getQuery()->getResult();
    }
}
