SF\SmartfixBundle\Entity\Service:
    type: entity
    table: null
    repositoryClass: SF\SmartfixBundle\Entity\ServiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        serviceName:
            type: string
            length: 255
            column: service_name
        avatar:
            type: string
            length: 255
        status:
            type: integer
        dateCreate:
            type: datetime
            column: date_create
    lifecycleCallbacks: {  }
