<?php

namespace Proxies\__CG__\StudentBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Student extends \StudentBundle\Entity\Student implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'id', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'name', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'image', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'age', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'render', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'position', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'schoolId', 'school', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'subject', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'brochure');
        }

        return array('__isInitialized__', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'id', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'name', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'image', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'age', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'render', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'position', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'schoolId', 'school', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'subject', '' . "\0" . 'StudentBundle\\Entity\\Student' . "\0" . 'brochure');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Student $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setAge($age)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAge', array($age));

        return parent::setAge($age);
    }

    /**
     * {@inheritDoc}
     */
    public function getAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', array());

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setRender($render)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRender', array($render));

        return parent::setRender($render);
    }

    /**
     * {@inheritDoc}
     */
    public function getRender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRender', array());

        return parent::getRender();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', array($position));

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', array());

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoolId($schoolId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoolId', array($schoolId));

        return parent::setSchoolId($schoolId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolId', array());

        return parent::getSchoolId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchool(\StudentBundle\Entity\School $school = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchool', array($school));

        return parent::setSchool($school);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchool()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchool', array());

        return parent::getSchool();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullImagePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullImagePath', array());

        return parent::getFullImagePath();
    }

    /**
     * {@inheritDoc}
     */
    public function uploadImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'uploadImage', array());

        return parent::uploadImage();
    }

    /**
     * {@inheritDoc}
     */
    public function moveImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'moveImage', array());

        return parent::moveImage();
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', array());

        return parent::removeImage();
    }

    /**
     * {@inheritDoc}
     */
    public function addSubject(\StudentBundle\Entity\Subject $subject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSubject', array($subject));

        return parent::addSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSubject(\StudentBundle\Entity\Subject $subject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSubject', array($subject));

        return parent::removeSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', array());

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function getBrochure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrochure', array());

        return parent::getBrochure();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrochure($brochure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrochure', array($brochure));

        return parent::setBrochure($brochure);
    }

}
