<?php

namespace Proxies\__CG__\SF\SmartfixBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ClientDevice extends \SF\SmartfixBundle\Entity\ClientDevice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'id', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'clientId', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'deviceId', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'operatingSystem', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'deviceToken', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'client', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'histories');
        }

        return array('__isInitialized__', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'id', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'clientId', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'deviceId', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'operatingSystem', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'deviceToken', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'client', '' . "\0" . 'SF\\SmartfixBundle\\Entity\\ClientDevice' . "\0" . 'histories');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ClientDevice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientId($clientId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientId', array($clientId));

        return parent::setClientId($clientId);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientId', array());

        return parent::getClientId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeviceId($deviceId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeviceId', array($deviceId));

        return parent::setDeviceId($deviceId);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeviceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeviceId', array());

        return parent::getDeviceId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperatingSystem($operatingSystem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperatingSystem', array($operatingSystem));

        return parent::setOperatingSystem($operatingSystem);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperatingSystem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperatingSystem', array());

        return parent::getOperatingSystem();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeviceToken($deviceToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeviceToken', array($deviceToken));

        return parent::setDeviceToken($deviceToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeviceToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeviceToken', array());

        return parent::getDeviceToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient($client = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', array($client));

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', array());

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistories($histories = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistories', array($histories));

        return parent::setHistories($histories);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistories', array());

        return parent::getHistories();
    }

}
