client:
    path:     /
    defaults: { _controller: "SmartfixBundle:Client:index" }

client_show:
    path:     /{id}/show
    defaults: { _controller: "SmartfixBundle:Client:show" }

client_new:
    path:     /new
    defaults: { _controller: "SmartfixBundle:Client:new" }

client_create:
    path:     /create
    defaults: { _controller: "SmartfixBundle:Client:create" , _format: ~}
    requirements:
        _method: POST|PUT

client_edit:
    path:     /{id}/edit
    defaults: { _controller: "SmartfixBundle:Client:edit" }

client_update:
    path:     /{id}/update
    defaults: { _controller: "SmartfixBundle:Client:update" }
    requirements: { _method: post|put }

client_delete:
    path:     /{id}/delete
    defaults: { _controller: "SmartfixBundle:Client:delete" }
    requirements: { _method: post|delete }
